---
- name: Install and start service
  hosts: all
  vars:
    - app: [yum,httpd,vim,telnet]
  become: true
  tasks:
    - name: Installing NGINX
      yum :
        name: "{{ item }}"
        state: present
      tags: i-nginx
      with_items: "{{ apps }}"
~
