---
- name: kill a process
  hosts: all
  become: true
  tasks:
    - name: Find a process and kill
      become: true
      ignore_errors: yes
      shell: "pgrep nginx | xargs kill"

    - name: start the service
      service:
        name: nginx
        state: started
        enabled: true
