---
- name: Install and start service
  hosts: all
  become: true
  tasks:
    - name: Installing NGINX
      yum :
        name: nginx
        state: present
    - name: Starting the nginx service
      service:
        name: nginx
        state: started
        enabled: true
