---
- name: set password
  hosts: all
  become: true
  tasks:
    - name: set passwd
      user:
        name: Dhruv
        update_password: always
        password: "{{'abc12345'| password_hash('sha512')}}"
